apiVersion: v1
kind: Service
metadata:
  name: node-app-rolling-service
spec:
  type: NodePort
  selector:
    app: node-app-rolling
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30081
