apiVersion: v1
kind: Service
metadata:
  name: node-app-canary-stable
spec:
  type: NodePort
  selector:
    app: node-app-canary
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30082
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-canary-canary
spec:
  type: ClusterIP
  selector:
    app: node-app-canary
  ports:
    - port: 80
      targetPort: 3000
